// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: internal/server/proto/vesta.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VestaServiceClient is the client API for VestaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VestaServiceClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
	DeploymentList(ctx context.Context, in *ListDeploymentRequest, opts ...grpc.CallOption) (*ListDeploymentResponse, error)
	CatalogList(ctx context.Context, in *CatalogListRequest, opts ...grpc.CallOption) (*CatalogListResponse, error)
	CatalogInspect(ctx context.Context, in *CatalogInspectRequest, opts ...grpc.CallOption) (*CatalogInspectResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (VestaService_SubscribeEventsClient, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	VolumeList(ctx context.Context, in *VolumeListRequest, opts ...grpc.CallOption) (*VolumeListResponse, error)
}

type vestaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVestaServiceClient(cc grpc.ClientConnInterface) VestaServiceClient {
	return &vestaServiceClient{cc}
}

func (c *vestaServiceClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, "/proto.VestaService/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vestaServiceClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, "/proto.VestaService/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vestaServiceClient) DeploymentList(ctx context.Context, in *ListDeploymentRequest, opts ...grpc.CallOption) (*ListDeploymentResponse, error) {
	out := new(ListDeploymentResponse)
	err := c.cc.Invoke(ctx, "/proto.VestaService/DeploymentList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vestaServiceClient) CatalogList(ctx context.Context, in *CatalogListRequest, opts ...grpc.CallOption) (*CatalogListResponse, error) {
	out := new(CatalogListResponse)
	err := c.cc.Invoke(ctx, "/proto.VestaService/CatalogList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vestaServiceClient) CatalogInspect(ctx context.Context, in *CatalogInspectRequest, opts ...grpc.CallOption) (*CatalogInspectResponse, error) {
	out := new(CatalogInspectResponse)
	err := c.cc.Invoke(ctx, "/proto.VestaService/CatalogInspect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vestaServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/proto.VestaService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vestaServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (VestaService_SubscribeEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VestaService_ServiceDesc.Streams[0], "/proto.VestaService/SubscribeEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &vestaServiceSubscribeEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VestaService_SubscribeEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type vestaServiceSubscribeEventsClient struct {
	grpc.ClientStream
}

func (x *vestaServiceSubscribeEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vestaServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/proto.VestaService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vestaServiceClient) VolumeList(ctx context.Context, in *VolumeListRequest, opts ...grpc.CallOption) (*VolumeListResponse, error) {
	out := new(VolumeListResponse)
	err := c.cc.Invoke(ctx, "/proto.VestaService/VolumeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VestaServiceServer is the server API for VestaService service.
// All implementations must embed UnimplementedVestaServiceServer
// for forward compatibility
type VestaServiceServer interface {
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error)
	DeploymentList(context.Context, *ListDeploymentRequest) (*ListDeploymentResponse, error)
	CatalogList(context.Context, *CatalogListRequest) (*CatalogListResponse, error)
	CatalogInspect(context.Context, *CatalogInspectRequest) (*CatalogInspectResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	SubscribeEvents(*SubscribeEventsRequest, VestaService_SubscribeEventsServer) error
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	VolumeList(context.Context, *VolumeListRequest) (*VolumeListResponse, error)
	mustEmbedUnimplementedVestaServiceServer()
}

// UnimplementedVestaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVestaServiceServer struct {
}

func (UnimplementedVestaServiceServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedVestaServiceServer) Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedVestaServiceServer) DeploymentList(context.Context, *ListDeploymentRequest) (*ListDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploymentList not implemented")
}
func (UnimplementedVestaServiceServer) CatalogList(context.Context, *CatalogListRequest) (*CatalogListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CatalogList not implemented")
}
func (UnimplementedVestaServiceServer) CatalogInspect(context.Context, *CatalogInspectRequest) (*CatalogInspectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CatalogInspect not implemented")
}
func (UnimplementedVestaServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedVestaServiceServer) SubscribeEvents(*SubscribeEventsRequest, VestaService_SubscribeEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedVestaServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedVestaServiceServer) VolumeList(context.Context, *VolumeListRequest) (*VolumeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeList not implemented")
}
func (UnimplementedVestaServiceServer) mustEmbedUnimplementedVestaServiceServer() {}

// UnsafeVestaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VestaServiceServer will
// result in compilation errors.
type UnsafeVestaServiceServer interface {
	mustEmbedUnimplementedVestaServiceServer()
}

func RegisterVestaServiceServer(s grpc.ServiceRegistrar, srv VestaServiceServer) {
	s.RegisterService(&VestaService_ServiceDesc, srv)
}

func _VestaService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VestaServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VestaService/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VestaServiceServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VestaService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VestaServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VestaService/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VestaServiceServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VestaService_DeploymentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VestaServiceServer).DeploymentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VestaService/DeploymentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VestaServiceServer).DeploymentList(ctx, req.(*ListDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VestaService_CatalogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VestaServiceServer).CatalogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VestaService/CatalogList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VestaServiceServer).CatalogList(ctx, req.(*CatalogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VestaService_CatalogInspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogInspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VestaServiceServer).CatalogInspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VestaService/CatalogInspect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VestaServiceServer).CatalogInspect(ctx, req.(*CatalogInspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VestaService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VestaServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VestaService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VestaServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VestaService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VestaServiceServer).SubscribeEvents(m, &vestaServiceSubscribeEventsServer{stream})
}

type VestaService_SubscribeEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type vestaServiceSubscribeEventsServer struct {
	grpc.ServerStream
}

func (x *vestaServiceSubscribeEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _VestaService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VestaServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VestaService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VestaServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VestaService_VolumeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VestaServiceServer).VolumeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VestaService/VolumeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VestaServiceServer).VolumeList(ctx, req.(*VolumeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VestaService_ServiceDesc is the grpc.ServiceDesc for VestaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VestaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VestaService",
	HandlerType: (*VestaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _VestaService_Apply_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _VestaService_Destroy_Handler,
		},
		{
			MethodName: "DeploymentList",
			Handler:    _VestaService_DeploymentList_Handler,
		},
		{
			MethodName: "CatalogList",
			Handler:    _VestaService_CatalogList_Handler,
		},
		{
			MethodName: "CatalogInspect",
			Handler:    _VestaService_CatalogInspect_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _VestaService_Ping_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _VestaService_Stop_Handler,
		},
		{
			MethodName: "VolumeList",
			Handler:    _VestaService_VolumeList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _VestaService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/server/proto/vesta.proto",
}
