version: "3.7"
services:
  babel:
    image: ghcr.io/umbracle/babel:v0.0.1
    command:
      - "--plugin"
      - "ethereum_el"
      - "server"
      - "url=http://0.0.0.0:8545"
    networks:
      - default
    labels:
      service: goerli-geth
      task: babel
  node:
    image: ethereum/client-go:v1.11.5
    command:
      - "--datadir"
      - "/data"
      - "--http.addr"
      - "0.0.0.0"
      - "--http"
      - "--http.port"
      - "8545"
      - "--http.vhosts"
      - "*"
      - "--http.corsdomain"
      - "*"
      - "--authrpc.addr"
      - "0.0.0.0"
      - "--authrpc.port"
      - "8551"
      - "--authrpc.vhosts"
      - "*"
      - "--authrpc.jwtsecret"
      - "/var/lib/jwtsecret/jwt.hex"
      - "--metrics.addr"
      - "0.0.0.0"
      - "--ipcdisable"
      - "--verbosity"
      - "3"
      - "--maxpeers"
      - "50"
      - "--syncmode"
      - "snap"
      - "--goerli"
      - "--metrics"
    configs:
      - source: file-0
        target: /var/lib/jwtsecret/jwt.hex
    networks:
      - default
    volumes:
      - type: bind
        source: /Users/ferranbt/go/src/github.com/umbracle/vesta/data-vesta/docker/volumes/d5223243-db58-f944-4bb2-9a5476270311
        target: /data
    labels:
      service: goerli-geth
      task: node
configs:
  file-0:
    file: /tmp/file-temp4140893920
networks:
  default:
    external: true
    name: sepolia-test
